In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Dataset.csv')

In [3]:
df.head()

,Unnamed: 0,Id,year,brand,full_model_name,model_name,price,distance_travelled(kms),fuel_type,city,...,new and less used,inv_car_price,inv_car_dist,inv_car_age,inv_brand,std_invprice,std_invdistance_travelled,std_invrank,best_buy1,best_buy2
0,0,0,2016,Honda,Honda Brio S MT,Brio,425000.0,9680.0,Petrol,Mumbai,...,0,2.352941e-06,0.000103,0.200000,0.142857,0.143417,0.035730,0.132143,677.134239,0.000000
1,1,1,2012,Nissan,Nissan Sunny XV Diesel,Sunny,325000.0,119120.0,Diesel,Mumbai,...,0,3.076923e-06,0.000008,0.111111,0.090909,0.188859,0.002496,0.079545,37.501318,0.000000
2,2,2,2017,Toyota,Toyota Fortuner 2.8 4x2 MT [2016-2020],Fortuner,2650000.0,64593.0,Diesel,Thane,...,0,3.773585e-07,0.000015,0.250000,1.000000,0.019416,0.004978,1.000000,96.646020,0.000000
3,3,3,2017,Mercedes-Benz,Mercedes-Benz E-Class E 220d Expression [2019-...,E-Class,4195000.0,25000.0,Diesel,Mumbai,...,1,2.383790e-07,0.000040,0.250000,0.500000,0.010692,0.013563,0.493750,71.604306,71.604306
4,4,4,2012,Hyundai,Hyundai Verna Fluidic 1.6 CRDi SX,Verna,475000.0,23800.0,Diesel,Mumbai,...,0,2.105263e-06,0.000042,0.111111,0.071429,0.127871,0.014269,0.059821,109.150857,0.000000

In [4]:
df.shape

(1725, 23)

In [5]:
df.columns

Index(['Unnamed: 0', 'Id', 'year', 'brand', 'full_model_name', 'model_name',
       'price', 'distance_travelled(kms)', 'fuel_type', 'city', 'brand_rank',
       'car_age', 'distance below 30k km', 'new and less used',
       'inv_car_price', 'inv_car_dist', 'inv_car_age', 'inv_brand',
       'std_invprice', 'std_invdistance_travelled', 'std_invrank', 'best_buy1',
       'best_buy2'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1725 entries, 0 to 1724
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Unnamed: 0                 1725 non-null   int64
 1   Id                         1725 non-null   int64
 2   year                       1725 non-null   int64
 3   brand                      1725 non-null   str
 4   full_model_name            1725 non-null   str
 5   model_name                 1725 non-null   str
 6   price                      1725 non-null   float64
 7   distance_travelled(kms)    1725 non-null   float64
 8   fuel_type                  1725 non-null   str
 9   city                       1725 non-null   str
 10  brand_rank                 1725 non-null   int64
 11  car_age                    1725 non-null   float64
 12  distance below 30k km      1725 non-null   int64
 13  new and less used          1725 non-null   int64
 14  inv_car_price              1725 non-null   float64
 15  inv_car_dist               1725 non-null   float64
 16  inv_car_age                1725 non-null   float64
 17  inv_brand                  1725 non-null   float64
 18  std_invprice               1725 non-null   float64
 19  std_invdistance_travelled  1725 non-null   float64
 20  std_invrank                1725 non-null   float64
 21  best_buy1                  1725 non-null   float64
 22  best_buy2                  1725 non-null   float64
dtypes: float64(12), int64(6), str(5)
memory usage: 403.7 KB

In [7]:
df.describe()

,Unnamed: 0,Id,year,price,distance_travelled(kms),brand_rank,car_age,distance below 30k km,new and less used,inv_car_price,inv_car_dist,inv_car_age,inv_brand,std_invprice,std_invdistance_travelled,std_invrank,best_buy1,best_buy2
count,1725.000000,1725.000000,1725.000000,1.725000e+03,1725.000000,1725.000000,1725.000000,1725.000000,1725.000000,1.725000e+03,1725.000000,1725.000000,1725.000000,1725.000000,1725.000000,1725.000000,1725.000000,1725.000000
mean,862.000000,862.000000,2015.390725,1.494837e+06,53848.256232,15.731014,5.609275,0.269565,0.209275,1.416237e-06,0.000041,inf,0.187810,0.084623,0.013809,0.177658,88.962902,32.537208
std,498.108924,498.108924,3.207504,1.671658e+06,44725.541963,12.951122,3.207504,0.443863,0.406909,1.291449e-06,0.000110,NaN,0.254849,0.081060,0.038689,0.258034,188.950690,158.662274
min,0.000000,0.000000,1990.000000,6.250000e+04,350.000000,1.000000,0.000000,0.000000,0.000000,6.802721e-08,0.000001,0.032258,0.012346,0.000000,0.000000,0.000000,0.000000,0.000000
25%,431.000000,431.000000,2013.000000,5.450000e+05,29000.000000,5.000000,3.000000,0.000000,0.000000,5.479452e-07,0.000014,0.125000,0.041667,0.030123,0.004524,0.029687,14.237358,0.000000
50%,862.000000,862.000000,2016.000000,8.750000e+05,49000.000000,14.000000,5.000000,0.000000,0.000000,1.142857e-06,0.000020,0.200000,0.071429,0.067464,0.006703,0.059821,36.716166,0.000000
75%,1293.000000,1293.000000,2018.000000,1.825000e+06,70500.000000,24.000000,8.000000,1.000000,0.000000,1.834862e-06,0.000034,0.333333,0.200000,0.110899,0.011631,0.190000,90.776658,0.000000
max,1724.000000,1724.000000,2021.000000,1.470000e+07,790000.000000,81.000000,31.000000,1.000000,1.000000,1.600000e-05,0.002857,inf,1.000000,1.000000,1.000000,1.000000,2477.517640,2477.517640

In [8]:
df = df.drop(columns=[
    "Unnamed: 0",
    "Id",
    "model_name",
    "brand_rank",
    "car_age",
    "distance below 30k km",
    "new and less used",
    "inv_car_price",
    "inv_car_dist",
    "inv_car_age",
    "inv_brand",
    "std_invprice",
    "std_invdistance_travelled",
    "std_invrank",
    "best_buy1",
    "best_buy2"
], errors="ignore")

In [9]:
df.dtypes

year                         int64
brand                          str
full_model_name                str
price                      float64
distance_travelled(kms)    float64
fuel_type                      str
city                           str
dtype: object

In [10]:
df['car_age_new']=2026-df['year']

In [11]:
df['car_age_new'].shape

(1725,)

In [12]:
df['car_age_new'].head()

0    10
1    14
2     9
3     9
4    14
Name: car_age_new, dtype: int64

In [13]:
df['km_per_year']=df['distance_travelled(kms)']/df['car_age_new'].clip(lower=1)
print(df[["year", "car_age_new", "distance_travelled(kms)", "km_per_year"]].head())

   year  car_age_new  distance_travelled(kms)  km_per_year
0  2016           10                   9680.0   968.000000
1  2012           14                 119120.0  8508.571429
2  2017            9                  64593.0  7177.000000
3  2017            9                  25000.0  2777.777778
4  2012           14                  23800.0  1700.000000

In [14]:
df=df.drop(columns=['year'])

In [15]:
X=df.drop('price',axis=1)
y=df['price']

In [16]:
X=pd.get_dummies(X,drop_first=True,dtype=int)

In [17]:
X.shape

(1725, 800)

In [18]:
y.shape

(1725,)

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
X_train.shape

(1380, 800)

In [22]:
y_train.shape

(1380,)

In [23]:
from sklearn.linear_model import LinearRegression

In [24]:
model=LinearRegression()

In [25]:
model.fit(X_train,y_train)

LinearRegression()

In [26]:
y_pred=model.predict(X_test)

In [27]:
y_pred

array([ 338981.43215808, 1603728.55271718,  967800.92542068,
       1094111.38517497, 1149146.25100879, 1162267.59071433,
        978777.51045548, 2634425.15193899, 2399999.99996562,
        990000.00012699,  404999.99985816, 1484660.44632973,
        949999.99967805,  484999.99995595,  815000.00002945,
       3482307.29600255,  910779.13430314,  550175.14994151,
        173841.04311584,  687696.12795807,  387117.53317698,
        841069.64558342, 5084635.18203546,  629120.63957435,
        792864.32895178,  434840.12105815,  431136.17945248,
        620805.34786581,  246718.78502235,  775651.52658217,
        320000.00008713, 3462268.24387096, 1445000.00011116,
        699000.00005681, 1491743.56326121,  525000.00003552,
        870000.00004717,  665079.54147907,  562917.51211132,
       1449999.99989997, 2765411.92240074, 1619359.74555777,
        439056.3553489 ,  413056.33018506,  814124.48344735,
        224999.99967064, 1010950.24872022,  790980.1165153 ,
        580000.00003842,  750000.00003219, 3698039.15089714,
       1094089.97211225, -107931.7460202 ,  858666.89170723,
        855920.1483517 ,  647617.94809492,  778499.06144759,
       1603728.55271718,  524903.35725421,  248135.25373658,
        726450.79392319, 2995752.03514819, 4347648.21801348,
       1149999.99945982,  344999.99993657,  787445.585401  ,
       2298970.49625836,   82658.54264095, 1405848.28286895,
        499999.99997632, 6190366.65543712, 1744311.72290849,
       1521598.38314349, 1119594.20041937, 2032300.89017012,
        444999.99999836,  404032.81798095,  915000.00004643,
       1354562.78035351, 2299046.76542415,  790980.1165153 ,
        379999.99998583, 4125641.01192903,  758775.93885878,
        396093.73862622,  429826.29574524, -172440.96422611,
       1001059.34521511, 4399999.99990597,  398878.60873932,
        680145.41677942,  739128.50360311, 1085375.77985407,
       4789638.13980173, 1263046.47786881, 3361170.47915632,
        525000.0001657 , -186704.25933888, 1794075.11840754,
        773724.33271431, 2700000.0004176 ,  739919.25142937,
        662371.78921853, 3850000.00033596, 1482074.20234881,
        243661.33149052, 1758168.31895967, 4152552.43230216,
        580000.00003842, 2393105.19298452, 3816944.0731646 ,
       1054636.27280535, 1465477.38742593, 1772559.72345159,
        801545.33732865, 1172050.29691802,  624999.99976478,
       3430808.1573321 , 4850000.00033668,  109391.09420035,
       1218951.05375413, 1284775.73792858, 7089689.94391518,
        224999.99967064, 2011285.81188236,  733602.1039384 ,
       5120915.14162059,  839667.00887114,  492512.47218233,
       1622803.80476875, 1362727.697987  ,  730606.6068124 ,
        939512.58146416, 2399999.99988954, 1149000.00015513,
       2750552.6234329 ,  956909.95741377, 2000000.0001558 ,
       2614149.69750449, 1577987.1000603 , 1834230.89324244,
       1885675.18832495, 1232129.83117043, 1076454.08565957,
       2000000.0001558 , 1064444.19495056, 1352319.96042671,
       4237773.9443491 ,  949185.65749058, 1861943.3331719 ,
        774370.94303776,  649581.53263656, 1395214.93531868,
        468365.21745577,  575629.55799533, 1215477.97521907,
        899999.99987378,  436040.16943515,  246718.78502235,
        800158.40360603, 2371166.94062835,  678487.82891507,
        457752.48115142, 1689536.93951953, 1732172.98885381,
        475000.00011138,  232067.76234029, 1235177.41230616,
       2765411.92240074,  585495.15243128, 2483594.62544918,
       1252631.5451127 ,  561079.35404082, 1507845.79644122,
        974999.9997868 , 3850000.00013457, 3915693.90778649,
       1395214.93531868, 1986893.78001092,  563197.39491918,
        127702.40919722,   76547.97654623,  623098.54057659,
       2039650.35661167,  550175.14994151, 2224413.5364815 ,
        579947.01933259,  875022.90659406, 3961007.88883136,
       2733268.20330577, 3337731.75719462,  444165.06349692,
       2590639.12241994,  456092.38589524, 1450980.31872825,
        280369.86500928, 6561942.96783693,  116857.31765459,
       1195472.77954148, 5516046.76482009, 1258500.05538372,
         42650.17293529, -164921.0852761 ,  729298.44348245,
        828192.5155058 ,  598249.37120963,  401983.04264959,
       2371166.94062835,  297959.01216585,  495098.57106394,
       2179336.84598641,  790717.09731352, 2715959.20722738,
         21498.27662777, 5735772.57405811,  535104.40564013,
        866785.11427689, 1976878.6090982 ,  453243.77475514,
       2283420.42094807,  607598.33108166, 3700000.00035821,
        818422.75256598, 1062650.7995303 ,  431772.32361044,
        974491.46804566,  534957.93751895, 5431579.22604163,
       2110565.75673843, 1358180.49491723, 1617689.99552418,
       1116802.39421005, 1319091.11096516, 2081117.94123127,
       1893231.22729217, 1900000.00049622, 3876944.39535724,
       2269139.61686837, 1218510.00392405, 1035875.51631485,
       5299999.99981291,  800774.85973727, 1004881.98375081,
        252069.48456784, 1503572.34423052, 1269839.61324659,
        587811.01540249,  523479.03717004, 2941528.25323466,
       5954715.94114848, 1840687.07598395,  837274.23402239,
       3301606.49739182,  887074.71501056,  681205.24859928,
       1537474.53999078,  258793.44701026, 1450000.00046127,
       3015854.3821918 , 1073754.04414696,  891786.67372926,
        414547.86884199, 4352967.60467332,  568999.99986125,
        551519.49039312,  379999.99998583, 4060748.34337165,
       5131375.30487101, 2075556.18195291, 1391739.72002556,
       3738223.53013255, 2790000.00000953,  413961.18893978,
        647377.28053009, 1022459.94697945,  827176.94211724,
        682173.2997681 , 1073754.04414696, -186704.25933888,
        346815.45092407, 1776697.42736728, 1690773.71185098,
       1027700.88545578,  359999.99996804, 1650000.00028177,
       2850000.00027387, 2941528.25323466,  515733.85799631,
       3475312.29592958, 3617391.24580811, 3963788.26035065,
        989586.88278498, 1509974.21248532, 1659569.98593517,
        508945.7994248 , 1505644.58206889, 1274999.99988178,
       3058098.87324024, 3993588.71001614, 2200907.28015348,
       2000887.16713726, 1337055.32923717,  814124.48344735,
         24307.4928159 , 3430808.1573321 ,  573503.00260324,
        882729.75813584, 3607030.90101844,  873041.49939456,
        737772.90589834,  435125.30948843, 3960893.25256732,
       1238174.5958543 ,  667430.47077159, 2582975.28978581,
        672136.18218511, 4562927.67053789, 1589999.99983212,
       4694330.61229229, 2005769.10594137, 1482074.20234881,
        695000.0000037 , 6949999.99969668,  575996.48058167,
        716605.8384114 , 2078892.28180925, 2809277.95086351,
       1258817.4645475 ,  580248.55327932,   48836.09781061,
        678487.82891507,  470000.00016704, 5630423.00026291,
        429232.47443969, 1171860.52898442, 2143581.60953446,
        515733.85799631,  429006.1474757 ,  435000.00012923,
       1446703.10866476, 1272793.18437061, 1129771.21178306,
       2011285.81188236, 2785980.55318052,  274581.44183041])

In [31]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [33]:
mae=mean_absolute_error(y_test,y_pred)

In [34]:
mae

316293.3545828752

In [35]:
mse=mean_squared_error(y_test,y_pred)

In [36]:
mse

927363457328.0251

In [37]:
r2=r2_score(y_test,y_pred)

In [38]:
r2

0.7237534649441837